# Form implementation generated from reading ui file '..\UI\mainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.0.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(652, 469)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setAutoFillBackground(False)
        self.centralWidget.setStyleSheet("#centralWidget{background-color: rgb(97, 97, 97);}")
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sideBar = SideBar(self.centralWidget)
        self.sideBar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sideBar.sizePolicy().hasHeightForWidth())
        self.sideBar.setSizePolicy(sizePolicy)
        self.sideBar.setMinimumSize(QtCore.QSize(0, 0))
        self.sideBar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sideBar.setStyleSheet("#sideBar{\n"
"    background-color: rgb(49, 203, 0);\n"
"}\n"
"\n"
"QPushButton{\n"
"    border: 1px solid orange;\n"
"    border-radius: 2px;\n"
"    background-color: rgb(35, 152, 0);\n"
"}")
        self.sideBar.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.sideBar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.sideBar.setLineWidth(0)
        self.sideBar.setObjectName("sideBar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sideBar)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.sideBar)
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setStyleSheet("QTabWidget::pane{\n"
"    border-top: 2px solid #C2C7CB;\n"
"}\n"
"QTabBar::tab{\n"
"    border: 1px solid red;\n"
"    padding: 5px;\n"
"    background-color: rgb(51, 167, 255);\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(49, 203, 0, 255), stop:1                     rgba(34, 135, 0, 255));\n"
"}\n"
"QTabBar::tab:selected{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(51, 124, 160, 255), stop:1 rgba(34, 135, 0, 255));\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar_2 = QtWidgets.QMenuBar(MainWindow)
        self.menuBar_2.setGeometry(QtCore.QRect(0, 0, 652, 21))
        self.menuBar_2.setObjectName("menuBar_2")
        self.menuFile = QtWidgets.QMenu(self.menuBar_2)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar_2)
        self.actionnest = QtGui.QAction(MainWindow)
        self.actionnest.setObjectName("actionnest")
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuBar_2.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionnest.setText(_translate("MainWindow", "nest"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
from ..sideBar import SideBar


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
